# Basic Python
# 1. Split this string

In [1]:
s = "Hi there Sam!"
s.split()
['Hi', 'there', 'dad!']

['Hi', 'there', 'dad!']

In [2]:
print()

# 2. Use .format() to print the following string.
# Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))
print()

The diameter of Earth is 12742 kilometers.



# 3. In this nest dictionary grab the word "hello"

In [4]:
dict1 = {'k1':'hello'}
dict2 = {'k1':{'k2':'hello'}}
dict3 = {'k1':[{'k2':['k3',['hello']]}]}
dict4 = {'k1':[1,2,{'k2':['k3',{'k4':[1,2,['hello']]}]}]}

# Numpy
**import numpy as np

# 4.1 Create an array of 10 zeros?
# 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
arr=np.zeros(10)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 7. Concatinate a and b
# a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)
print(np.concatenate((a,b)))

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


# Pandas
# 8. Create a dataframe with 3 rows and 2 columns

In [10]:
import pandas as pd
df = pd.DataFrame()
print(df)
print()

Empty DataFrame
Columns: []
Index: []



# 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:

import datetime
import pandas as pd
date=datetime.datetime.strptime(“01-01-2023”,”%d-%m-%Y”)
periods= datetime.datetime.strptime(“10-02-2023”,”%d-%m-%Y”)
date_gen=pd.date_range(date,periods)
print(date_gen.strftime(”%d-%m-%Y”))

SyntaxError: invalid character in identifier (3390791200.py, line 3)

# 10. Create 2D list to DataFrame
# lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
Import pandas as pd
lists==[[1,’aaa’,22], [2,’bbb’,25], [3,’ccc’,24]]
df=pd.DataFrame(lists,columns=[‘ID’,’Name’,’Age’])
print(df)